name: frontend
description: Application de réservation pour restaurant "les AL"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.1.0

  # State management
  provider: ^6.1.1

  # Stockage local sécurisé pour le token
  flutter_secure_storage: ^9.0.0

  # Pour les formulaires
  email_validator: ^2.1.17

  # Icons
  cupertino_icons: ^1.0.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (images, fonts, etc.)
  assets:
    - assets/images/